@startuml
class DiExtentions <<static>> {
    + {static} AddServices(services:IServiceCollection) : IServiceCollection
    + {static} AddSingletons(services:IServiceCollection) : IServiceCollection
    + {static} AddScopeds(services:IServiceCollection) : IServiceCollection
    + {static} AddGrpc(services:IServiceCollection) : IServiceCollection
    + {static} AddSwaggerStaf(services:IServiceCollection) : IServiceCollection
    + {static} AddDatabase(services:IServiceCollection) : IServiceCollection
    + {static} AddLogger(builder:WebApplicationBuilder) : void
}
@enduml
