@startuml
class GetChanelMessagesQuery {
    + PageSize : int <<get>> <<set>>
    + PageNumber : int <<get>> <<set>>
}
class "IRequest`1"<T> {
}
"IRequest`1" "<PaginationModel<MessageViewDto>>" <|-- GetChanelMessagesQuery
GetChanelMessagesQuery --> "ChanelId" Guid
GetChanelMessagesQuery --> "FromDate" DateTime
GetChanelMessagesQuery --> "ToDate" DateTime
@enduml
