@startuml
class RemoveClientCommand {
    + Path : string <<get>> <<set>>
    + ConnectionId : string? <<get>> <<set>>
    + IsInput : bool <<get>> <<set>> = false
}
class "IRequest`1"<T> {
}
"IRequest`1" "<bool>" <|-- RemoveClientCommand
@enduml
