// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using UniversalBroker.Core.Database.Models;

namespace UniversalBroker.Core.Database.Models.Configurations
{
    public partial class CommunicationAttributeConfiguration : IEntityTypeConfiguration<CommunicationAttribute>
    {
        public void Configure(EntityTypeBuilder<CommunicationAttribute> entity)
        {
            entity.HasKey(e => e.Id).HasName("communication_attributes_pkey");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Connection).WithMany(p => p.CommunicationAttributes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkcommunicat873537");

            entity.HasOne(d => d.Attribute).WithOne(p => p.CommunicationAttribute)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkcommunicat305228");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CommunicationAttribute> entity);
    }
}
