// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using UniversalBroker.Core.Database.Models;

namespace UniversalBroker.Core.Database.Models.Configurations
{
    public partial class ConnectionAttributeConfiguration : IEntityTypeConfiguration<ConnectionAttribute>
    {
        public void Configure(EntityTypeBuilder<ConnectionAttribute> entity)
        {
            entity.HasKey(e => e.Id).HasName("connection_attributes_pkey");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Connection).WithMany(p => p.ConnectionAttributes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkconnection831720");

            entity.HasOne(d => d.Attribute).WithOne(p => p.ConnectionAttribute)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkconnection949414");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ConnectionAttribute> entity);
    }
}
