// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using UniversalBroker.Core.Database.Models;

namespace UniversalBroker.Core.Database.Models.Configurations
{
    public partial class ConnectionConfiguration : IEntityTypeConfiguration<Connection>
    {
        public void Configure(EntityTypeBuilder<Connection> entity)
        {
            entity.HasKey(e => e.Id).HasName("connections_pkey");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Communication).WithMany(p => p.Connections)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkconnection291121");

            entity.HasMany(d => d.Chanels).WithMany(p => p.Connections)
                .UsingEntity<Dictionary<string, object>>(
                    "ConnectionChanel",
                    r => r.HasOne<Chanel>().WithMany()
                        .HasForeignKey("ChanelId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("fkconnection846733"),
                    l => l.HasOne<Connection>().WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("fkconnection167592"),
                    j =>
                    {
                        j.HasKey("ConnectionId", "ChanelId").HasName("connection_chanels_pkey");
                        j.ToTable("connection_chanels");
                        j.IndexerProperty<Guid>("ConnectionId").HasColumnName("connection_id");
                        j.IndexerProperty<Guid>("ChanelId").HasColumnName("chanel_id");
                    });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Connection> entity);
    }
}
