// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using UniversalBroker.Core.Database.Models;

namespace UniversalBroker.Core.Database.Models.Configurations
{
    public partial class ExecutionLogConfiguration : IEntityTypeConfiguration<ExecutionLog>
    {
        public void Configure(EntityTypeBuilder<ExecutionLog> entity)
        {
            entity.HasKey(e => e.Id).HasName("execution_logs_pkey");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Script).WithMany(p => p.ExecutionLogs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkexecution_526194");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ExecutionLog> entity);
    }
}
