// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using UniversalBroker.Core.Database.Models;

namespace UniversalBroker.Core.Database.Models.Configurations
{
    public partial class MessageConfiguration : IEntityTypeConfiguration<Message>
    {
        public void Configure(EntityTypeBuilder<Message> entity)
        {
            entity.HasKey(e => e.Id).HasName("messages_pkey");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Connection).WithMany(p => p.Messages).HasConstraintName("fkmessages186526");

            entity.HasOne(d => d.SourceChannel).WithMany(p => p.MessageSourceChannels).HasConstraintName("fkmessages608833");

            entity.HasOne(d => d.TargetChannel).WithMany(p => p.MessageTargetChannels).HasConstraintName("fkmessages582656");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Message> entity);
    }
}
