// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using UniversalBroker.Core.Database.Models;

namespace UniversalBroker.Core.Database.Models.Configurations
{
    public partial class ScriptConfiguration : IEntityTypeConfiguration<Script>
    {
        public void Configure(EntityTypeBuilder<Script> entity)
        {
            entity.HasKey(e => e.Id).HasName("scripts_pkey");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Chanel).WithOne(p => p.Script)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fkscripts802619");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Script> entity);
    }
}
