@startuml
class GetConnectionQueryHandler {
    + <<async>> Handle(request:GetConnectionQuery, cancellationToken:CancellationToken) : Task<ConnectionFullDto>
}
class "ILogger`1"<T> {
}
class "IRequestHandler`2"<T1,T2> {
}
"IRequestHandler`2" "<GetConnectionQuery,ConnectionFullDto>" <|-- GetConnectionQueryHandler
GetConnectionQueryHandler o-> "_logger" ILogger
GetConnectionQueryHandler o-> "_mapper" IMapper
GetConnectionQueryHandler o-> "_context" BrockerContext
@enduml
