@startuml
interface IMainService {
    StartWork(CancellationTokenSource:CancellationTokenSource) : Task<SemaphoreSlim>
    SendMessage(coreMessage:CoreMessage, cancellationToken:CancellationToken) : Task
}
IMainService --> "Communication" CommunicationFullDto
@enduml
