@startuml
class SubscribeOnTopicCommandHandler {
    + <<async>> Handle(request:SubscribeOnTopicCommand, cancellationToken:CancellationToken) : Task
    - <<async>> SendInformationToCore(connectionDto:ConnectionDto, cancellationToken:CancellationToken) : Task
}
class "ILogger`1"<T> {
}
class "IRequestHandler`1"<T> {
}
"IRequestHandler`1" "<SubscribeOnTopicCommand>" <|-- SubscribeOnTopicCommandHandler
SubscribeOnTopicCommandHandler o-> "_logger" ILogger
SubscribeOnTopicCommandHandler o-> "_mediator" IMediator
SubscribeOnTopicCommandHandler o-> "_rabbitMqService" IRabbitMqService
SubscribeOnTopicCommandHandler o-> "_initService" IInitService
@enduml
