// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniversalBroker.Core.Database.Models;

[Table("attributes")]
public partial class Attribute
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Required]
    [StringLength(255)]
    public string Key { get; set; }

    [Column("value")]
    public string Value { get; set; }

    [InverseProperty("Attribute")]
    public virtual CommunicationAttribute CommunicationAttribute { get; set; }

    [InverseProperty("Attribute")]
    public virtual ConnectionAttribute ConnectionAttribute { get; set; }
}