// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniversalBroker.Core.Database.Models;

[Table("chanels")]
public partial class Chanel
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [InverseProperty("SourceChannel")]
    public virtual ICollection<Message> MessageSourceChannels { get; set; } = new List<Message>();

    [InverseProperty("TargetChannel")]
    public virtual ICollection<Message> MessageTargetChannels { get; set; } = new List<Message>();

    [InverseProperty("Chanel")]
    public virtual Script Script { get; set; }

    [ForeignKey("ChanelId")]
    [InverseProperty("Chanels")]
    public virtual ICollection<Connection> Connections { get; set; } = new List<Connection>();

    [ForeignKey("ToChanelId")]
    [InverseProperty("ToChanels")]
    public virtual ICollection<Chanel> FromChanels { get; set; } = new List<Chanel>();

    [ForeignKey("FromChanelId")]
    [InverseProperty("FromChanels")]
    public virtual ICollection<Chanel> ToChanels { get; set; } = new List<Chanel>();
}