// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniversalBroker.Core.Database.Models;

[Table("communications")]
public partial class Communication
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("type_identifier")]
    public Guid TypeIdentifier { get; set; }

    [Required]
    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [Column("description")]
    public string Description { get; set; }

    [Column("status")]
    public bool Status { get; set; }

    [InverseProperty("Connection")]
    public virtual ICollection<CommunicationAttribute> CommunicationAttributes { get; set; } = new List<CommunicationAttribute>();

    [InverseProperty("Communication")]
    public virtual ICollection<Connection> Connections { get; set; } = new List<Connection>();
}