// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniversalBroker.Core.Database.Models;

[Table("connections")]
public partial class Connection
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("communication_id")]
    public Guid CommunicationId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [Column("isinput")]
    public bool Isinput { get; set; }

    [Required]
    [Column("path")]
    public string Path { get; set; }

    [ForeignKey("CommunicationId")]
    [InverseProperty("Connections")]
    public virtual Communication Communication { get; set; }

    [InverseProperty("Connection")]
    public virtual ICollection<ConnectionAttribute> ConnectionAttributes { get; set; } = new List<ConnectionAttribute>();

    [InverseProperty("Connection")]
    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    [ForeignKey("ConnectionId")]
    [InverseProperty("Connections")]
    public virtual ICollection<Chanel> Chanels { get; set; } = new List<Chanel>();
}