// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniversalBroker.Core.Database.Models;

[Table("connection_attributes")]
public partial class ConnectionAttribute
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("connection_id")]
    public Guid ConnectionId { get; set; }

    [ForeignKey("ConnectionId")]
    [InverseProperty("ConnectionAttributes")]
    public virtual Connection Connection { get; set; }

    [ForeignKey("Id")]
    [InverseProperty("ConnectionAttribute")]
    public virtual Attribute Attribute { get; set; }
}