// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniversalBroker.Core.Database.Models;

[Table("execution_logs")]
public partial class ExecutionLog
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("datetime")]
    public DateTime Datetime { get; set; }

    [Required]
    [Column("lavel")]
    [StringLength(255)]
    public string Lavel { get; set; }

    [Required]
    [Column("text")]
    public string Text { get; set; }

    [Column("script_id")]
    public Guid ScriptId { get; set; }

    [ForeignKey("ScriptId")]
    [InverseProperty("ExecutionLogs")]
    public virtual Script Script { get; set; }
}