// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniversalBroker.Core.Database.Models;

[Table("headers")]
public partial class Header
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [Required]
    [Column("value")]
    public string Value { get; set; }

    [Column("messages_id")]
    public Guid MessagesId { get; set; }

    [ForeignKey("MessagesId")]
    [InverseProperty("Headers")]
    public virtual Message Messages { get; set; }
}