// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniversalBroker.Core.Database.Models;

[Table("messages")]
public partial class Message
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("datetime")]
    public DateTime Datetime { get; set; }

    [Required]
    [Column("data")]
    public byte[] Data { get; set; }

    [Column("connection_id")]
    public Guid? ConnectionId { get; set; }

    [Column("source_channel_id")]
    public Guid? SourceChannelId { get; set; }

    [Column("target_channel_id")]
    public Guid? TargetChannelId { get; set; }

    [ForeignKey("ConnectionId")]
    [InverseProperty("Messages")]
    public virtual Connection Connection { get; set; }

    [InverseProperty("Messages")]
    public virtual ICollection<Header> Headers { get; set; } = new List<Header>();

    [ForeignKey("SourceChannelId")]
    [InverseProperty("MessageSourceChannels")]
    public virtual Chanel SourceChannel { get; set; }

    [ForeignKey("TargetChannelId")]
    [InverseProperty("MessageTargetChannels")]
    public virtual Chanel TargetChannel { get; set; }
}