// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniversalBroker.Core.Database.Models;

[Table("scripts")]
public partial class Script
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Required]
    [Column("path")]
    [StringLength(255)]
    public string Path { get; set; }

    [InverseProperty("Script")]
    public virtual ICollection<ExecutionLog> ExecutionLogs { get; set; } = new List<ExecutionLog>();

    [ForeignKey("Id")]
    [InverseProperty("Script")]
    public virtual Chanel Chanel { get; set; }
}